name: CI

on:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install Buildozer Dependencies
      run: |
        pip install --user --upgrade buildozer
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          git \
          libffi-dev \
          libssl-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libsqlite3-dev

    - name: Initialize Buildozer
      run: buildozer init

    - name: Build APK
      run: tree ~\home
