name: CI

on:
  push:
    branches:
      - workflow

jobs:
  build-android:
    runs-on: ubuntu-22.04
    if: false

    steps:
      - name: Install Buildozer Dependencies
        run: |
          pip install --user --upgrade buildozer
          sudo apt-get update
          pip install cython
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libssl-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libsqlite3-dev
            ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "build-tools;29.0.0"

      - name: Checkout-Repository
        uses: actions/checkout@v2

      - name: Build APK
        run: |
          cd ./src
          echo y | buildozer -v android debug

  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install pygame
          pip install numpy
          pip install z3-solver
          export Z3_LIBRARY_PATH=/home/runner/.local/lib/python3.10/site-packages/z3/lib/

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build EXE for Linux
        run: |
          cd ./src
          pyinstaller main.spec

      - name: Upload Artifact for Linux
        uses: actions/upload-artifact@v2
        with:
          name: your_script_linux_exe
          path: ./src/dist/main

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install pygame
          pip install numpy
          pip install z3-solver

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build EXE for Windows
        run: |
          cd ./src
          pyinstaller main.spec

      - name: Upload Artifact for Windows
        uses: actions/upload-artifact@v2
        with:
          name: your_script_windows_exe
          path: ./src/dist/main.exe

  build_macos:
    runs-on: macos-latest

    steps:
      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install pygame
          pip install numpy
          pip install z3-solver

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build APP for macOS
        run: |
          cd ./src
          pyinstaller main.spec

      - name: Upload Artifact for macOS
        uses: actions/upload-artifact@v2
        with:
          name: your_script_macos_app
          path: ./src/dist/main.app
